package inventory.model;
// Generated Aug 29, 2019 8:13:42 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String email;
	private String name;
	private int activeFlag;
	private Date createDate;
	private Date updateDatae;
	private Set userRoles = new HashSet(0);
	private Integer RoleId;

	public Users() {
	}

	public Users(String username, String password, String name, int activeFlag, Date createDate, Date updateDatae) {
		this.username = username;
		this.password = password;
		this.name = name;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.updateDatae = updateDatae;
	}

	public Users(String username, String password, String email, String name, int activeFlag, Date createDate,
			Date updateDatae, Set userRoles) {
		this.username = username;
		this.password = password;
		this.email = email;
		this.name = name;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.updateDatae = updateDatae;
		this.userRoles = userRoles;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDatae() {
		return this.updateDatae;
	}

	public void setUpdateDatae(Date updateDatae) {
		this.updateDatae = updateDatae;
	}

	public Set getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set userRoles) {
		this.userRoles = userRoles;
	}

	public Integer getRoleId() {
		return RoleId;
	}

	public void setRoleId(Integer roleId) {
		RoleId = roleId;
	}
	

}
